### ISSUE TITLE
Support StreamDeserializer

### ISSUE THREAD

**Issue by oberien** [MaulingMonkey/json-spanned-value#6]
Would it be possible to add support for [serde_json's `StreamDeserializer`](https://docs.rs/serde_json/1.0.58/serde_json/de/struct.StreamDeserializer.html)?

**Comment by MaulingMonkey** [comment]
Hmm... *might* be as simple as wrapping [StreamDeserializer::new](https://docs.rs/serde_json/1.0.58/serde_json/de/struct.StreamDeserializer.html#method.new)...

**Comment by MaulingMonkey** [comment]
Needed a wrapper to properly implement iterator advancement: [`json_spanned_value::StreamDeserializer`](https://docs.rs/json-spanned-value/0.2.2/json_spanned_value/struct.StreamDeserializer.html).  Published as `0.2.2`.  I'm being lazy and skipping [`serde_json::de::Deserializer`](https://docs.rs/serde_json/1.0.58/serde_json/de/struct.Deserializer.html) until explicitly requested ;)

ce989f865b48c60a9a18aedf7a3183e9a5aabc3b Wrap StreamDeserializer
47f33bc0d84e07c34d70d9bc65e5b3f552e733fe  Make StreamDeserializer able to implement RefUnwindSafe + Send + Sync + ...
f68925d39408d4ca60ef96c9cf6ace576e8f9eff v0.2.2

**Comment by MaulingMonkey** [comment]
Oh, I'll also note the API is *slightly* different at the moment - pass in a `&str` or `&[u8]` or other `AsRef<[u8]>` directly to new without wrapping it in `IoRead` / `StrRead` / `SliceRead`.  Examples in the unit tests: https://github.com/MaulingMonkey/json-spanned-value/blob/47f33bc0d84e07c34d70d9bc65e5b3f552e733fe/src/tests.rs#L194-L228

**Comment by oberien** [comment]
Wow, that was a very fast response and implementation :+1: Thanks a lot! I'll test it out tomorrow.

**Comment by MaulingMonkey** [comment]
You managed to catch me *exactly* when I was checking github 😄.  Let me know if you run into any issues with it.

**Comment by oberien** [comment]
It works perfectly fine, thanks again!
